---

-   name: Common configuration
    hosts: all
    user: root

    roles:
        - common

-   name: Configure jBPM servers
    hosts: jbpmservers
    user: root

    roles:
       - java
       #        - jbpm

#-   name: Configure MediaManager servers
#    hosts: mmservers
#    user: root

#    roles:
#        - mm

-   name: Configure ActiveMQ servers
    hosts: activemqservers
    user: root

    roles:
        - java
#        - activemq

-   name: Configure Database servers
    hosts: dbservers
    user: root

    roles:
        - db

-   name: Configure MediaManager build servers
    hosts: mmbuildservers
    user: root

    roles:
        - db
        - apache
        - php
        - php-pecl
        - php-pear
        - composer
        - mediamanager
