---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel").
php_enablerepo: "remi"
php_memory_limit: "256M"
php_max_execution_time: "60"
php_upload_max_filesize: "64M"
php_apc_cache_by_default: "1"
php_apc_shm_size: "96M"
php_date_timezone: "Europe/Amsterdam"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-pdo
  - php-pear
  - php-pecl-apc
  - php-xml
  - php-xmlrpc
  - php-mysql
