---
### main.yml - ActiveMQ role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#
- name: Download ActiveMQ
  get_url: url=http://ftp.nluug.nl/internet/apache/activemq/apache-activemq/5.8.0/apache-activemq-5.8.0-bin.tar.gz
      dest=/tmp/apache-activemq-5.8.0-bin.tar.gz mode=0440

- name: Unzip ActiveMQ
  command: tar -C /opt -xf /tmp/apache-activemq-5.8.0-bin.tar.gz

- name: Create simlink to ActiveMQ
  file: src=/opt/apache-activemq-5.8.0 dest=/opt/activemq owner=root group=root state=link

- name: Copy activemq.xml configuration file
  copy: src=activemq.xml dest=/opt/activemq/conf/ owner=root group=root mode=0644

- name: Copy jetty.xml configuration file
  copy: src=jetty.xml dest=/opt/activemq/conf/ owner=root group=root mode=0644

- name: Copy configuration file to start and stop ActiveMQ
  copy: src=activemq dest=/etc/default/activemq owner=root group=root mode=0755

- name: Copy init.d file to start and stop ActiveMQ
  copy: src=activemq.init.d dest=/etc/rc.d/init.d/activemq owner=root group=root mode=0755

- name: Start and Enable ActiveMQ
  service: name=activemq state=started enabled=yes
