---
# Remi yum repository.
- name: Download Epel 6
  get_url: dest=/tmp/ url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: Download Remi repo.
  get_url: dest=/tmp/ url=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: Install Repos
  command: rpm -Uvh --force /tmp/remi-release-6*.rpm /tmp/epel-release-6*.rpm

- name: Install rxvt terminal
  yum: name=rxvt-unicode-256color state=installed

- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ ntp_timezone }}  dest=/etc/localtime state=link force=yes

- name: Install NTP
  yum: name=ntp state=installed

- name: Ensure NTP is running.
  service: name=ntpd state=started enabled=yes

- name: Install libselinux-python
  yum: name=libselinux-python state=installed

- name: Disable iptables
  command: chkconfig iptables off

- name: iptables running
  service: name=iptables state=stopped

- name: set selinux boolean
  command: /usr/sbin/setsebool -P httpd_can_network_connect=1

- name: install compilers
  yum: name={{ item }} state=installed
  with_items:
      - gcc
      - gcc-c++
      - autoconf
      - automake
      - openssl-devel

- name: Install Git
  yum: name=git state=installed

